name: Pre-commit auto-update

on:
  schedule:
    - cron: '0 3 * * 1'

jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run pre-commit autoupdate
        run: pre-commit autoupdate

      - name: Commit updates and create PR
        run: |
          git clone https://github.com/E3SM-Project/mache.git
          # Configure git using GitHub Actions credentials.
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git checkout -b update-pre-commit-deps
          git add .pre-commit-config.yaml
          git commit -m "Update pre-commit dependencies" .pre-commit-config.yaml
          git push origin update-pre-commit-deps
          gh pr create --title "Update `pre-commit` and its dependencies" --body "This PR was automatically created to update pre-commit and its dependencies."
        env:
          GH_TOKEN: ${{ github.token }}

